monitor.alsa.rules = [
  {
    matches = [
      { api.alsa.card.name = "acp" }
    ]
    actions = {
      update-props = {
        api.alsa.use-acp = false
        priority.driver = 4000
        priority.session = 4000
      }
    }
  }
]
