[metadata]
name = "channels"
description = "Select a television channel"
requirements = ["eza"]

[source]
command = "eza --sort name --oneline ${XDG_CONFIG_HOME:-$HOME/.config}/television/cable | sed 's/\\.toml$//' | grep -Fvx channels"
no_sort = true

[ui]
layout = "portrait"
preview_panel = { hidden = true }

[keybindings]
enter = "actions:select"

[actions.select]
command = "tv {}"
mode = "execute"
