[metadata]
name = "dirs"
description = "A channel to select directories"
requirements = ["fd", "eza"]

[source]
command = "fd --type directory --follow --hidden --max-depth 2"

[preview]
command = "eza --tree --color=always '{}' | head -200"

[keybindings]
enter = "actions:change"

[actions.change]
command = "echo '{}' > /tmp/tv-jump && kill -SIGUSR1 $PPID"
mode = "execute"
