[metadata]
name = "files"
description = "A channel to select files"
requirements = ["fd", "bat"]

[source]
command = "fd --type file --follow --hidden"

[preview]
command = "bat -n --color=always --line-range :256 '{}'"

[keybindings]
enter = "actions:edit"

[actions.edit]
command = "zeditor '{}'"
mode = "execute"
