[metadata]
name = "git-repo"
description = "A channel to select from git repositories"
requirements = ["fd", "git"]

[source]
command = "fd '^.git$' ~/repo ~/projects -u --type directory --hidden --max-depth 5 --prune --exec echo {//}"
display = "{split:/:-1}"

[preview]
command = "git -C '{}' log -n 200 --pretty=medium --all --graph --color"

[keybindings]
enter = "actions:change"

[actions.change]
command = "echo '{}' > /tmp/tv-jump && kill -SIGUSR1 $PPID"
mode = "execute"
