[metadata]
name = "text"
description = "A channel to find and select text from files"
requirements = ["rg", "bat"]

[source]
command = "rg . --column --line-number --no-heading --color=always --smart-case"
ansi = true
output = "{strip_ansi|split:\\::..2}"

[preview]
command = "bat -n --color=always --line-range :256 '{strip_ansi|split:\\::0}'"
offset = '{strip_ansi|split:\::1}'

[ui]
preview_panel = { header = '{strip_ansi|split:\::..2}', size = 70 }

[keybindings]
enter = "actions:edit"

[actions.edit]
command = "zeditor '{strip_ansi|split:\\::0}:{strip_ansi|split:\\::1}:{strip_ansi|split:\\::2}'"
mode = "execute"
