[metadata]
name = "wallpaper"
description = "Select and set wallpaper"
requirements = ["eza", "hyprpaper"]

[source]
command = "eza --oneline ~/pictures/.wallpaper"

[ui]
layout = "portrait"
preview_panel = { hidden = true }

[keybindings]
enter = "actions:select"

[actions.select]
command = "zsh -c '$HOME/.local/bin/set-wallpaper \"{}\"'"
mode = "execute"
