[metadata]
name = "wallpaper"
description = "Select and set wallpaper"
requirements = ["eza", "hyprpaper"]

[source]
command = "eza --oneline ~/pictures/.wallpaper"
no_sort = true

[ui]
layout = "portrait"
preview_panel = { hidden = true }

[keybindings]
enter = "actions:select"

[actions.select]
command = "set-wallpaper '{}'"
mode = "execute"
