[cpu]
governor=powersave
energy_performance_preference=performance
boost=1

[audio]
timeout=0

[usb]
autosuspend=0

[vm]
transparent_hugepages=madvise

[sysctl]
kernel.nmi_watchdog=0
vm.swappiness=10
vm.vfs_cache_pressure=50
vm.laptop_mode=0
kernel.sched_autogroup_enabled=1
