[[entries]]
default = true
name = "Bing"
url = "https://bing.com/search?q=%TERM%"
icon = "/home/rsp/.local/icons/bing.svg"

[[entries]]
default = true
name = "Copilot"
url = "https://bing.com/copilotsearch?q=%TERM%"
icon = "/home/rsp/.local/icons/copilot.svg"

[[entries]]
default = true
name = "Gemini"
url = "https://google.com/search?sourceid=chrome&udm=50&aep=42&q=%TERM%"
icon = "/home/rsp/.local/icons/gemini.svg"

[[entries]]
default = true
name = "Google Search"
url = "https://unduck.link?q=%TERM%"
icon = "/home/rsp/.local/icons/google.svg"
