ao=pulse
audio-device=pulse/easyeffects_sink
audio-format=float
audio-samplerate=48000
audio-wait-open=no
audio-stream-silence=yes
audio-pitch-correction=yes
audio-normalize-downmix=yes
audio-resampler=soxr
audio-swresample-o=cheby=1,precision=28
af=lavfi=[loudnorm=I=-16:TP=-1.0:LRA=9]
vo=gpu-next
hwdec=auto-safe
vd-lavc-threads=0
