monitor = eDP-1,1920x1080@60,0x0,1

bind = SUPER, RETURN, exec, uwsm-app -- alacritty
bind = SUPER, E, exec, uwsm-app -- zeditor
bind = SUPER, C, exec, uwsm-app -- google-chrome-stable

bind = SUPER, B, exec, uwsm-app -- chromium
bind = SUPER, I, exec, uwsm-app -- chromium --incognito

bind = SUPER, W, killactive,
bind = SUPER, U, exec, uwsm-app -- easyeffects
bind = SUPER, F, exec, uwsm-app -- nautilus --new-window
bind = SUPER, P, exec, uwsm-app -- auto-cpufreq-gtk

bind = ,INSERT, exec, uwsm-app -- sh -c 'grim -g "$(slurp)" -t png - | tee "$HOME/shared/clips/$(date +%Y%m%d_%H%M%S).png" | wl-copy -t image/png'
bind = ,PRINT, exec, uwsm-app -- sh -c 'grim -t png - | tee "$HOME/shared/capture/$(date +%Y%m%d_%H%M%S).png" | wl-copy -t image/png'

exec-once = uwsm finalize
exec-once = uwsm-app -s b -- easyeffects --hide-window --service-mode

bind = SUPER, TAB, workspace, previous
bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5
bind = SUPER, 6, workspace, 6
bind = SUPER, 7, workspace, 7
bind = SUPER, 8, workspace, 8
bind = SUPER, 9, workspace, 9
bind = SUPER, 0, workspace, 10
bind = SUPER SHIFT, 1, movetoworkspace, 1
bind = SUPER SHIFT, 2, movetoworkspace, 2
bind = SUPER SHIFT, 3, movetoworkspace, 3
bind = SUPER SHIFT, 4, movetoworkspace, 4
bind = SUPER SHIFT, 5, movetoworkspace, 5
bind = SUPER SHIFT, 6, movetoworkspace, 6
bind = SUPER SHIFT, 7, movetoworkspace, 7
bind = SUPER SHIFT, 8, movetoworkspace, 8
bind = SUPER SHIFT, 9, movetoworkspace, 9
bind = SUPER SHIFT, 0, movetoworkspace, 10
bind = SUPER SHIFT, right, movetoworkspace, +1
bind = SUPER SHIFT, left, movetoworkspace, -1
bind = SUPER, left, movefocus, l
bind = SUPER, right, movefocus, r
bind = SUPER, up, movefocus, u
bind = SUPER, down, movefocus, d

bindel = ,XF86MonBrightnessDown, exec, brightnessctl -e4 -n2 set 2%-
bindel = ,XF86MonBrightnessUp, exec, brightnessctl -e4 -n2 set 2%+
bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindl = ,XF86AudioPrev, exec, playerctl previous
bindl = ,XF86AudioPlay, exec, playerctl play-pause
bindl = ,XF86AudioNext, exec, playerctl next

general {
    border_size = 0
    gaps_in = 0
    gaps_out = 0
    snap {
        enabled = true
    }
}

decoration {
    blur {
        enabled = false
    }
    shadow {
        enabled = false
    }
}

animations {
    enabled = false
}

input {
    follow_mouse = 1
}

misc {
    disable_hyprland_logo = true
    force_default_wallpaper = 1
    font_family = "Geist"
    key_press_enables_dpms = true
    mouse_move_enables_dpms = true
    vfr = true
}

windowrule {
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}
