general {
  after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({action = "enable"})'
  on_lock_cmd = hyprctl dispatch 'hl.dsp.dpms({action = "disable"})'
  on_unlock_cmd = hyprctl dispatch 'hl.dsp.dpms({action = "enable"})'
  inhibit_sleep = 1
}

listener {
  timeout = 60
  on-timeout = brightnessctl -sd rgb:kbd_backlight set 0
  on-resume = brightnessctl -rd rgb:kbd_backlight
}

listener {
  timeout = 120
  on-timeout = hyprctl dispatch 'hl.dsp.dpms({action = "disable"})'
  on-resume = hyprctl dispatch 'hl.dsp.dpms({action = "enable"})'
}

listener {
  timeout = 240
  on-timeout = systemctl suspend
}
