--disk-cache-dir=/run/user/1000/google-chrome-dev
--disk-cache-size=134217728
--enable-gpu-rasterization
--enable-zero-copy
--enable-features=Vulkan,DefaultANGLEVulkan,VulkanFromANGLE,FluentOverlayScrollbar,FluentScrollbar
