--disk-cache-size=268435456
--sync-url=https://chrome-sync.sandbox.google.com/chrome-sync/alpha
--enable-features=V8VmFuture,AcceleratedVideoEncoder,VaapiVideoDecoder,VaapiIgnoreDriverChecks,Vulkan,VulkanFromANGLE,DefaultANGLEVulkan,WebRtcPipeWireCamera,ParallelDownloading
--enable-zero-copy
--enable-smooth-scrolling
--enable-gpu-rasterization
--enable-experimental-web-platform-features
--javascript-harmony
--password-store=gnome-libsecret
--disable-component-update
--component-updater=disable-background-updates
--disable-features=OptimizationGuideOnDeviceModel
