--disk-cache-dir=/run/user/1000/google-chrome
--disk-cache-size=268435456
--enable-gpu-rasterization
--enable-zero-copy
--enable-features=AcceleratedVideoEncoder,AcceleratedVideoDecodeLinuxGL,VaapiVideoDecodeLinuxGL,VaapiVideoDecoder,VaapiIgnoreDriverChecks,Vulkan,DefaultANGLEVulkan,VulkanFromANGLE,FluentOverlayScrollbar,FluentScrollbar
