--disk-cache-dir=/run/user/1000/helium-browser
--disk-cache-size=268435456
--ozone-platform=wayland
--password-store=gnome-libsecret
--enable-zero-copy
--enable-gpu-rasterization
--enable-smooth-scrolling
--javascript-harmony
--enable-experimental-web-platform-features
--enable-features=V8VmFuture,WaylandSessionManagement,AcceleratedVideoEncoder,VaapiVideoDecoder,VaapiIgnoreDriverChecks,Vulkan,VulkanFromANGLE,DefaultANGLEVulkan,WebRtcPipeWireCamera,SymphoniaAudioDecoding,SymphoniaMp3Decoding,SymphoniaPcmDecoding,SymphoniaVorbisDecoding,ParallelDownloading,TreesInViz,LinkPreview,PasskeyUnlockErrorUi,PasskeyUnlockManager,SearchNavigationPrefetch,SearchPrefetchServicePrefetching,DiskCacheBackendExperiment
