--disk-cache-dir=/run/user/1000/helium-browser
--disk-cache-size=268435456
--ozone-platform=wayland
--password-store=gnome-libsecret
--enable-gpu-rasterization
--enable-zero-copy
--energy-saver-fps-limit=60
--enable-features=WaylandSessionManagement,ReduceUserAgentDataLinuxPlatformVersion,RendererSideContentDecoding,AcceleratedVideoEncoder,WebRtcPipeWireCamera,TreesInViz,SearchNavigationPrefetch,SearchPrefetchServicePrefetching,BackgroundResourceFetch,NewContentForCheckerboardedScrolls,ThrottleMainFrameTo60Hz
--disable-features=HeliumNoiseAudio,HeliumNoise,WebRtcAllowInputVolumeAdjustment
