[env]
TERM = "xterm-256color"

[window]
padding = { x = 8, y = 4 }
dynamic_padding = true
decorations = "None"
startup_mode = "Windowed"

[cursor]
style = { shape = "Beam", blinking = "always" }
thickness = 0.15

[mouse]
hide_when_typing = true

[font]
size = 11
normal = { family = "Geist Mono" }
italic = { family = "Geist Mono" }
bold = { family = "Geist Mono" }
bold_italic = { family = "Geist Mono" }

[colors]
primary = { foreground = "#f2f3f4", background = "#020304" }
cursor = { cursor = "#3090f0" }
line_indicator = { foreground = "#020304", background = "#f2f3f4" }
footer_bar = { foreground = "#020304", background = "#f2f3f4" }

[colors.normal]
black = "#a4a5a6"
white = "#f2f3f4"
red = "#e25099"
yellow = "#e0a278"
green = "#62c073"
cyan = "#4aacc0"
blue = "#6969f9"
magenta = "#a658f5"

[colors.bright]
black = "#a4a5a6"
white = "#f2f3f4"
red = "#e25099"
yellow = "#e0a278"
green = "#62c073"
cyan = "#4aacc0"
blue = "#6969f9"
magenta = "#a658f5"

[hints]
alphabet = "asdfghjkl"

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "U", mods = "Control" }
regex = "(https?|git|ssh|ftp)://[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`\\\\]+"

[keyboard]
bindings = [
  { key = "V", mods = "Control|Shift", action = "Paste" },
  { key = "C", mods = "Control|Shift", action = "Copy" },

  { key = "Equals", mods = "Control", action = "IncreaseFontSize" },
  { key = "Minus", mods = "Control", action = "DecreaseFontSize" },
  { key = "0", mods = "Control", action = "ResetFontSize" },

  { key = "F", mods = "Control|Shift", action = "SearchForward" },
  { key = "B", mods = "Control|Shift", action = "SearchBackward" },

  { key = "PageUp", mods = "Shift", action = "ScrollPageUp" },
  { key = "PageDown", mods = "Shift", action = "ScrollPageDown" },
  { key = "Home", mods = "Shift", action = "ScrollToTop" },
  { key = "End", mods = "Shift", action = "ScrollToBottom" },

  { key = "K", mods = "Control|Shift", action = "ClearHistory" },
  { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
]
