tick_rate = 50
default_channel = "files"
history_size = 200
global_history = false

[ui]
ui_scale = 100
orientation = "landscape"
theme = "default"

[ui.theme_overrides]
background = '#020304'
border_fg = '#171819'
text_fg = '#f2f3f4'
dimmed_text_fg = '#a4a5a6'
input_text_fg = '#4aacc0'
result_count_fg = '#171819'
result_name_fg = '#a4a5a6'
result_line_number_fg = '#171819'
result_value_fg = '#4aacc0'
selection_fg = '#f2f3f4'
selection_bg = '#242526'
match_fg = '#e25099'
preview_title_fg = '#a658f5'
channel_mode_fg = '#020304'
channel_mode_bg = '#62c073'
remote_control_mode_fg = '#020304'
remote_control_mode_bg = '#e0a278'
send_to_channel_mode_fg = '#4aacc0'

[ui.input_bar]
position = "top"
prompt = "~"
padding = { left = 1, right = 1, top = 0, bottom = 0 }
border_type = "rounded"

[ui.status_bar]
hidden = true

[ui.results_panel]
border_type = "rounded"
padding = { left = 1, right = 1, top = 0, bottom = 0 }

[ui.preview_panel]
size = 50
scrollbar = true
border_type = "rounded"
hidden = false

[ui.help_panel]
show_categories = true
hidden = true

[ui.remote_control]
show_channel_descriptions = true
sort_alphabetically = true

[keybindings]
esc = "quit"
down = "select_next_entry"
up = "select_prev_entry"
ctrl-up = "select_prev_history"
ctrl-down = "select_next_history"
tab = "toggle_selection_down"
backtab = "toggle_selection_up"
enter = "confirm_selection"
pagedown = "scroll_preview_half_page_down"
pageup = "scroll_preview_half_page_up"
ctrl-f = "cycle_previews"
ctrl-y = "copy_entry_to_clipboard"
ctrl-r = "reload_source"
ctrl-s = "cycle_sources"
ctrl-t = "toggle_remote_control"
ctrl-o = "toggle_preview"
ctrl-h = "toggle_help"
f12 = "toggle_status_bar"
ctrl-l = "toggle_layout"
backspace = "delete_prev_char"
delete = "delete_next_char"
left = "go_to_prev_char"
right = "go_to_next_char"
home = "go_to_input_start"
end = "go_to_input_end"

[shell_integration]
fallback_channel = "files"
